server:
  servlet:
    context-path: /api/v1/
  port: 8092
spring:
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: http://localhost:8090/login/oauth2/code/keycloak
        registration:
          keycloak:
            client-secret: kDYGM9e0mpPsdQRlyMSg6tDQ92cJl9UO
            client-id: ms-partial-client
            authorization-grant-type: client_credentials
            redirect-uri: http://localhost:8080/login/oauth2/code/keycloak
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/parcial-realm
  application:
    name: ms-users
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
keycloak:
  serverUrl: http://localhost:8080/
  realm: master
  clientId: admin-cli
  clientSecret: XwUuxDY5tfDkD4017S6iv1wbk9KI1mIB
  user: admin
  password: admin
  realmApp: parcial-realm
  jwkset:
    url: http://localhost:8080/realms/parcial-realm/protocol/openid-connect/certs
